id: t5-small.0613.t5_sentinel.b

mode: training

epochs: 15

backbone:
  name: t5-small
  model_max_length: 512

dataset:
  - label: Human
    token: <extra_id_0>
    token_id: 32099
    root: data/split/human-text
  - label: Gemini
    token: <extra_id_1>
    token_id: 32098
    root: data/split/gemini-text
  - label: GPT
    token: <extra_id_2>
    token_id: 32097
    root: data/split/gpt-text
  - label: Deepseek
    token: <extra_id_3>
    token_id: 32096
    root: data/split/deepseek-text
  - label: Llama
    token: <extra_id_4>
    token_id: 32095
    root: data/split/llama-text
  - label: Gemini + Human
    token: <extra_id_5>
    token_id: 32094
    root: data/split/gemini-human-text
  - label: GPT + Human
    token: <extra_id_6>
    token_id: 32093
    root: data/split/gpt-human-text
  - label: Deepseek + Human
    token: <extra_id_7>
    token_id: 32092
    root: data/split/deepseek-human-text
  - label: Llama + Human
    token: <extra_id_8>
    token_id: 32091
    root: data/split/llama-human-text

dataloader:
  batch_size: 16
  num_workers: 8

tokenizer:
  padding: true
  truncation: true
  return_tensors: pt

optimizer:
  lr: 1.0e-4
  weight_decay: 5.0e-5
  batch_size: 128
